# Generated by Django 6.0 on 2025-12-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nrc', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('dui', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('giro', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nrc', models.CharField(max_length=20, unique=True)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('es_importador', models.BooleanField(default=False)),
                ('email_lectura', models.EmailField(blank=True, help_text='Correo donde llegan los DTEs de proveedores', max_length=254, null=True)),
                ('clave_correo', models.CharField(blank=True, help_text='Contraseña de aplicación para leer el correo', max_length=100, null=True)),
                ('hora_sync', models.TimeField(default='03:00:00', help_text='Hora automática de lectura')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(default='03', max_length=2)),
                ('codigo_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nrc_proveedor', models.CharField(max_length=20)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('monto_gravado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_percepcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clasificacion_1', models.CharField(default='Gravada', max_length=50)),
                ('clasificacion_2', models.CharField(blank=True, max_length=50)),
                ('clasificacion_3', models.CharField(blank=True, max_length=50)),
                ('periodo_aplicado', models.CharField(max_length=7)),
                ('estado', models.CharField(default='Registrado', max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_recibidas', to='api.cliente')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('periodo_aplicado', models.CharField(max_length=7)),
                ('sello_recepcion', models.CharField(blank=True, max_length=100, null=True)),
                ('nrc_emisor', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_retencion', models.CharField(choices=[('161', 'Retención Tarjeta (Anexo 6)'), ('162', 'Retención IVA 1% (Anexo 7)')], default='162', max_length=3)),
                ('codigo_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_emisor', models.CharField(max_length=200)),
                ('nit_emisor', models.CharField(max_length=20)),
                ('monto_sujeto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_retenido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('periodo_aplicado', models.CharField(max_length=7)),
                ('tipo_venta', models.CharField(choices=[('CF', 'Consumidor Final'), ('CCF', 'Contribuyente')], max_length=10)),
                ('clase_documento', models.CharField(choices=[('1', 'Impreso por Imprenta'), ('2', 'Formulario Único'), ('3', 'Ticket / Máquina Registradora'), ('4', 'Documento Electrónico (DTE)')], default='1', max_length=2)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_control', models.CharField(blank=True, max_length=100, null=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=100, null=True)),
                ('serie_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_formulario_unico', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_control_desde', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_control_hasta', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_receptor', models.CharField(blank=True, max_length=200, null=True)),
                ('nrc_receptor', models.CharField(blank=True, max_length=20, null=True)),
                ('venta_gravada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('venta_exenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('venta_no_sujeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('debito_fiscal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva_retenido_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva_retenido_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clasificacion_venta', models.CharField(default='1', max_length=20)),
                ('tipo_ingreso', models.CharField(default='3', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_hechas', to='api.cliente')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to='api.empresa')),
            ],
        ),
    ]
