# Generated by Django 6.0.1 on 2026-01-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cod_establecimiento',
            field=models.CharField(default='M001', help_text='Código de establecimiento (Ej: M001)', max_length=4),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cod_punto_venta',
            field=models.CharField(default='P001', help_text='Código de punto de venta (Ej: P001)', max_length=4),
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto de la empresa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(default='06', help_text='Código de departamento de 2 dígitos (Ej: 06 para San Salvador)', max_length=2),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(default='14', help_text='Código de municipio de 2 dígitos (Ej: 14 para San Salvador)', max_length=2),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto de la empresa', max_length=20, null=True),
        ),
    ]
