# Generated by Django 6.0.1 on 2026-01-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agregar_campos_emisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.CharField(help_text="Tipo de DTE: '01' = Factura Consumidor Final, '03' = Crédito Fiscal", max_length=2)),
                ('anio', models.IntegerField(help_text='Año del correlativo (se reinicia automáticamente cada año)')),
                ('ultimo_correlativo', models.IntegerField(default=0, help_text='Último número correlativo utilizado para este tipo de DTE en este año')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este correlativo', on_delete=django.db.models.deletion.CASCADE, related_name='correlativos', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Correlativo DTE',
                'verbose_name_plural': 'Correlativos DTE',
                'ordering': ['empresa', 'tipo_dte', '-anio'],
                'indexes': [models.Index(fields=['empresa', 'tipo_dte', 'anio'], name='api_correla_empresa_0a1975_idx')],
                'unique_together': {('empresa', 'tipo_dte', 'anio')},
            },
        ),
    ]
