# Generated by Django 6.0.1 on 2026-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(default='06', help_text='Código de departamento de 2 dígitos (Ej: 06 para San Salvador)', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(default='14', help_text='Código de municipio de 2 dígitos (Ej: 14 para San Salvador)', max_length=2),
        ),
    ]
