# Generated by Django 6.0.1 on 2026-01-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cliente_departamento_cliente_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_actividad',
            field=models.CharField(blank=True, help_text='Código de Actividad Económica según CAT-019 (Ej: 45201 para Reparación mecánica de automotores)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='desc_actividad',
            field=models.CharField(blank=True, help_text='Descripción de la Actividad Económica (Ej: Reparación mecánica de automotores)', max_length=150, null=True),
        ),
    ]
