# Generated by Django 6.0.2 on 2026-02-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_venta_cliente_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gran_contribuyente',
            field=models.BooleanField(default=False, help_text='Si es gran contribuyente y mismo giro que emisor, aplica IVA Percibido 1%'),
        ),
    ]
