# Generated by Django 6.0.2 on 2026-02-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_gran_contribuyente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='correo_receptor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_receptor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='documento_receptor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_doc_receptor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
