# Generated by Django 6.0.2 on 2026-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_hora_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='error_envio_mensaje',
            field=models.CharField(blank=True, help_text='Último error al enviar a MH (timeout, red, servidor caído)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_dte',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Generado', 'Generado'), ('Enviado', 'Enviado'), ('AceptadoMH', 'Aceptado por MH'), ('RechazadoMH', 'Rechazado por MH'), ('ErrorEnvio', 'Error de envío (reintentar)'), ('Anulado', 'Anulado')], default='Borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('CCF', 'Contribuyente'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito')], default='CCF', max_length=10),
        ),
    ]
