# Generated by Django 5.2.11 on 2026-02-22 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_infraestructura_produccion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='producto_empresa_codigo_uniq',
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('NIT', 'NIT'), ('DUI', 'DUI'), ('Pasaporte', 'Pasaporte')], default='NIT', help_text='Tipo de documento de identidad según MH', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_dte',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Generado', 'Generado'), ('Enviado', 'Enviado'), ('AceptadoMH', 'Aceptado por MH'), ('RechazadoMH', 'Rechazado por MH'), ('ErrorEnvio', 'Error de envío (reintentar)'), ('PendienteEnvio', 'Pendiente de envío (MH no disponible)'), ('Anulado', 'Anulado')], default='Borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('CCF', 'Contribuyente'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('FSE', 'Factura Sujeto Excluido')], default='CCF', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__isnull', False), models.Q(('codigo', ''), _negated=True)), fields=('empresa', 'codigo'), name='producto_empresa_codigo_uniq'),
        ),
    ]
