# Generated by Django 5.2.11 on 2026-02-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_empresa_to_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nrc',
            field=models.CharField(blank=True, help_text='NRC del cliente (obligatorio solo para Contribuyentes)', max_length=20, null=True),
        ),
    ]
