# Generated by Django 5.2.11 on 2026-02-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_nrc_unique_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cod_actividad_receptor',
            field=models.CharField(blank=True, help_text='Código actividad económica del receptor (para CCF)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='condicion_operacion',
            field=models.IntegerField(default=1, help_text='1=Contado, 2=Crédito, 3=Otro'),
        ),
        migrations.AddField(
            model_name='venta',
            name='desc_actividad_receptor',
            field=models.CharField(blank=True, help_text='Descripción actividad económica del receptor (para CCF)', max_length=250, null=True),
        ),
    ]
