# Generated by Django 5.2.11 on 2026-02-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_condicion_operacion_actividad_receptor_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='periodo_pago',
            field=models.CharField(blank=True, help_text='Unidad de periodo: 01=Días, 02=Semanas, 03=Meses, 04=Años', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='plazo_pago',
            field=models.CharField(blank=True, help_text="Número de plazo (ej: '30')", max_length=20, null=True),
        ),
    ]
