# Generated by Django 5.2.11 on 2026-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_plazo_periodo_pago_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='codigo_generacion_referenciado',
            field=models.CharField(blank=True, help_text='codigoGeneracion del DTE original referenciado (NC/ND apunta aquí al DTE que modifica)', max_length=100, null=True),
        ),
    ]
