# Generated by Django 5.2.11 on 2026-02-22 03:26

import django.db.models.deletion
from django.db import migrations, models


# Migra roles del campo 'rol' de PerfilUsuario → Grupos Django.
# Mapeo:  MASTER / ADMINISTRADOR → grupo 'Administrador'
#         VENDEDOR               → grupo 'Vendedor'
# Si el usuario ya pertenece al grupo no se duplica (add es idempotente).
def migrar_roles_a_grupos(apps, schema_editor):
    PerfilUsuario = apps.get_model('api', 'PerfilUsuario')
    Group = apps.get_model('auth', 'Group')

    grupo_admin, _ = Group.objects.get_or_create(name='Administrador')
    grupo_contador, _ = Group.objects.get_or_create(name='Contador')
    grupo_vendedor, _ = Group.objects.get_or_create(name='Vendedor')

    for perfil in PerfilUsuario.objects.select_related('user').all():
        rol = (perfil.rol or '').upper()
        if rol in ('MASTER', 'ADMINISTRADOR', 'ADMIN'):
            perfil.user.groups.add(grupo_admin)
        elif rol == 'CONTADOR':
            perfil.user.groups.add(grupo_contador)
        else:
            # VENDEDOR o sin rol: grupo Vendedor por defecto
            perfil.user.groups.add(grupo_vendedor)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_codigo_generacion_referenciado_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['empresa', 'user__username'], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        # PRIMERO: migrar datos de rol→grupos antes de eliminar el campo
        migrations.RunPython(migrar_roles_a_grupos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Perfil activo. Desactivar en lugar de eliminar.'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa del usuario. Vacío solo para superusuarios (ven todas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.empresa'),
        ),
    ]
