# Generated by Django 5.2.11 on 2026-02-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_ambiente_emision_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre visible de la plantilla (ej. Alquiler Mensual)', max_length=200)),
                ('tipo_dte', models.CharField(choices=[('01', 'Factura Consumidor Final'), ('03', 'Crédito Fiscal')], default='01', help_text='Tipo de DTE que se generará al usar la plantilla (01=CF, 03=CCF)', max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente asignado por defecto a la plantilla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_factura', to='api.cliente')),
                ('empresa', models.ForeignKey(help_text='Empresa dueña de la plantilla', on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_factura', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Plantilla de Factura',
                'verbose_name_plural': 'Plantillas de Factura',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_libre', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_libre', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('numero_item', models.IntegerField(default=1)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.plantillafactura')),
                ('producto', models.ForeignKey(blank=True, help_text='Producto asociado (opcional). Si no se indica, se usa descripcion_libre.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto')),
            ],
            options={
                'ordering': ['plantilla', 'numero_item', 'id'],
            },
        ),
    ]
