# Generated by Django 5.2.11 on 2026-03-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_actualizar_plantillas_email_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillafactura',
            options={'ordering': ['empresa', 'orden', 'nombre'], 'verbose_name': 'Plantilla de Factura', 'verbose_name_plural': 'Plantillas de Factura'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='contingencia_activa',
            field=models.BooleanField(default=False, help_text='Si está activa, los DTE se generan pero NO se envían a MH (quedan PendienteEnvio).'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contingencia_f_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin de la contingencia MH.', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contingencia_f_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la contingencia MH.', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contingencia_h_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin de la contingencia MH.', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contingencia_h_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio de la contingencia MH.', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contingencia_motivo',
            field=models.CharField(blank=True, help_text='motivoContingencia enviado a MH.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contingencia_tipo',
            field=models.IntegerField(blank=True, help_text='tipoContingencia (1–5) según catálogo MH.', null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_asunto_default',
            field=models.CharField(blank=True, default='Factura electrónica de {{nombre_empresa}} - {{codigo_generacion}}', help_text='Asunto del correo. Variables: {{numero_control}}, {{codigo_generacion}}, {{nombre_empresa}}, {{cliente}}, {{fecha}}', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_template_html',
            field=models.TextField(blank=True, default='<p>Estimado(a) {{cliente}},</p><p>Adjuntamos su factura electrónica ("{{codigo_generacion}}") por parte de {{nombre_empresa}}.</p><p>Puede descargar el documento PDF y el archivo JSON correspondientes que se encuentran adjuntos en este correo para sus registros.</p><p>Saludos cordiales.</p>', help_text='Plantilla HTML del cuerpo. Variables: {{cliente}}, {{numero_control}}, {{codigo_generacion}}, {{nombre_empresa}}, {{fecha}}, {{total}}', null=True),
        ),
    ]
