# Generated by Django 5.2.11 on 2026-06-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_empresa_tipo_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='acceso_posagil',
            field=models.BooleanField(default=False, help_text='Muestra en AgilDTE el acceso al módulo PosAgil (botón Abrir Pos Agil).'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='facturacion_solo_pos',
            field=models.BooleanField(default=False, help_text='Oculta la facturación nativa de AgilDTE; la emisión DTE se hace vía PosAgil.'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='documento_relacionado_fecha_emision',
            field=models.DateField(blank=True, help_text='fechaEmision (YYYY-MM-DD) del DTE relacionado para NC/ND', null=True),
        ),
    ]
